# Generated by Django 6.0 on 2026-03-21 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Codigo', models.CharField(max_length=150, unique=True)),
                ('Categoria', models.CharField(max_length=150)),
                ('Producto', models.CharField(max_length=250)),
                ('Precio_1kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Precio_1_4kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Precio_100kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Moneda', models.CharField(max_length=100)),
                ('fecha_de_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['fecha_de_registro'],
            },
        ),
    ]
