# Generated by Django 6.0 on 2026-05-09 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventario',
            name='id',
        ),
        migrations.AlterField(
            model_name='inventario',
            name='Codigo',
            field=models.CharField(max_length=150, primary_key=True, serialize=False, unique=True),
        ),
    ]
