# Generated by Django 6.0 on 2026-05-09 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_remove_inventario_id_alter_inventario_codigo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventario',
            old_name='Precio_100kg',
            new_name='Precio_100g',
        ),
        migrations.RenameField(
            model_name='inventario',
            old_name='Precio_1_4kg',
            new_name='Precio_1_4g',
        ),
    ]
