# Generated by Django 6.0 on 2026-05-09 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_rename_precio_100kg_inventario_precio_100g_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventario',
            name='Moneda',
        ),
        migrations.RemoveField(
            model_name='inventario',
            name='Precio_100g',
        ),
        migrations.RemoveField(
            model_name='inventario',
            name='Precio_1_4g',
        ),
        migrations.RemoveField(
            model_name='inventario',
            name='Precio_1kg',
        ),
        migrations.RemoveField(
            model_name='inventario',
            name='Producto',
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.IntegerField()),
                ('Precio_1kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Precio_1_4g', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Precio_100g', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Moneda', models.CharField(max_length=100)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.inventario')),
            ],
        ),
    ]
